baseURL = "https://pripramudya.com"
title = "#pripramudya"
author = "Pribadi Pramudya"
languageCode = "en-US"
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
enableRobotsTXT = true

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Blog Pengembangan Diri Melalui Keterampilan Digital"
  title = "Pribadi Pramudya Blog"
